### ISSUE TITLE
Need to specify expected behavior for UUID generation

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/uprotocol-spec#33]
The [UUID spec](https://github.com/eclipse-uprotocol/uprotocol-spec/blame/4cc618f6a0bc4bcbd42314b52449a1a17ce23577/basics/uuid.adoc#L76) defines that within each millisecond a maximum of 4095 distinct UUIDs can be generated. However, it is unclear what the expected behavior is when that limit is reached, e.g. is a uEntity supposed to be able to send messages having the same UUID at that point? Or does this mean that each uEntity can send *at most* 4095 messages per millisecond and once this limit is reached, it has to wait for the clock progressing to the next millisecond before it can send additional messages?

Even if this question seems rather hypothetical due to the (usually) limited processing power available in a vehicle, it would still make implementing an SDK much more robust and predictable.

**Comment by stevenhartley** [comment]
Hi @sophokles73 , 
Yes the uE can sent at most 4095 messages/1ms. If/when they reach that limit, the count stays at 4095 is how I coded it in Java. It might result in duplicate IDs but not in practice. We wanted to make the ID generation as simple and efficient as possible.

**Comment by sophokles73** [comment]
Ok, then we keep the way it is currently implemented in the Rust SDK as well.
